<a href="https://colab.research.google.com/github/itsmeaby/Machine-Learning/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensores

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3031, 0.6919, 0.9311, 0.1165],
        [0.5405, 0.3995, 0.3673, 0.5107],
        [0.8302, 0.2752, 0.5674, 0.9366]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # hieght, width, colour channels (R,G,B)
random_image_size_tensor

tensor([[[0.3818, 0.1655, 0.1288,  ..., 0.2181, 0.7808, 0.3759],
         [0.2416, 0.7033, 0.7474,  ..., 0.8369, 0.8191, 0.4308],
         [0.0670, 0.8327, 0.1423,  ..., 0.7506, 0.5092, 0.5772],
         ...,
         [0.9824, 0.0158, 0.9316,  ..., 0.4048, 0.4888, 0.9279],
         [0.5115, 0.6134, 0.4922,  ..., 0.8297, 0.1864, 0.3946],
         [0.7560, 0.7761, 0.6138,  ..., 0.6159, 0.6711, 0.0388]],

        [[0.4249, 0.2629, 0.8214,  ..., 0.9546, 0.3633, 0.5621],
         [0.9627, 0.1537, 0.4463,  ..., 0.1282, 0.0523, 0.6695],
         [0.4323, 0.8963, 0.4506,  ..., 0.6169, 0.6022, 0.7857],
         ...,
         [0.6357, 0.1201, 0.4601,  ..., 0.8468, 0.7050, 0.1404],
         [0.6983, 0.4716, 0.3188,  ..., 0.1595, 0.0907, 0.0390],
         [0.3738, 0.7119, 0.2154,  ..., 0.4233, 0.1224, 0.4992]],

        [[0.0422, 0.0356, 0.5015,  ..., 0.1267, 0.2430, 0.2940],
         [0.8030, 0.4440, 0.4166,  ..., 0.0541, 0.3236, 0.3877],
         [0.7808, 0.7022, 0.6868,  ..., 0.9726, 0.8613, 0.

In [19]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [20]:
# Creating a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tesor and tensors-like

In [24]:
torch.range(0,10)

<ipython-input-24-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**NOTE:** Tensor datatypes is one of the big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,  # what data type is tensor
                               device=None, # what device is tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
ten = float_16_tensor * float_32_tensor

In [32]:
ten.ndim, ten.shape

(1, torch.Size([3]))

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensor (tensor attributes)

In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9741, 0.1389, 0.4507, 0.7442],
        [0.2485, 0.0974, 0.3261, 0.1386],
        [0.2486, 0.4342, 0.1275, 0.9033]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [36]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor


tensor([1, 2, 3])

In [39]:
# Substract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try oyt PyTorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks anddeep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of **outer dimentions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
tensor @ tensor  # we can you (* or @) for matrix multiplication

tensor(14)

In [44]:
# Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [45]:
# Matrix multiplication manually
1*1 + 2*2 + 3*3

14

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.6 ms, sys: 83 µs, total: 1.68 ms
Wall time: 2.15 ms


tensor(14)

In [47]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 74 µs, sys: 0 ns, total: 74 µs
Wall time: 77.7 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [48]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm is the same as torch.matmul (it's as alias for writing less code)


In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimentions of the given tensor.

In [50]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [51]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

print(f"new shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")

print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimentions must match")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(f"output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimentions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
output shape: torch.Size([3, 3])


## Finding the min, max , mean, sum (tensor aggregation)

In [53]:
# create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [54]:
# find min
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [55]:
# find max
torch.max(x) , x.max(x)

(tensor(91), tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]))

In [57]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x)

RuntimeError: ignored

In [58]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [59]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## finding the positional min and max


In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# Find the position in tensor that has minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(91)

## Reshaping , stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - reshape a view of an input tensor of certain shape but keep the same memeory ad the original tnsor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimentions from a tensor
* Unsqueeze - add all `1` dimentions to a tensor
* Permute - Return a view of the input with dimentions permuted (swapped) in a certain way

In [65]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# Add an extra dimention -> the rashpe has to be compatible with original size
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# changing z changes x ( beacause a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z ,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [69]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [70]:
# torch.squeeze() -> removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n new tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

 new tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [71]:
# torch.unsqueeze() -> add a single dimensions to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n new tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 new tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [72]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifted axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [74]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with NumPy.

In [75]:
# Create a tensor

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Let's index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [80]:
# let's index on the most inner bracket (last dimention)
x[0][0][0]

tensor(1)

In [82]:
x[0][1][1]

tensor(5)

In [83]:
x[0][2][2]

tensor(9)

In [84]:
# You can also use ":" to select "all" of a target dimention
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
# Get all value's of the 0 dimention but only the 1 index value of the 1st and 2ed dimention
x[:,1,1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dimention and all value of 2ed dimention
x[0,0,:]

tensor([1, 2, 3])

In [88]:
#Index on x to return 9
x[:,2,2]

tensor([9])

In [89]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and NumPy

Numpy is a popular scintific python numerical conputing library.

Ans because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [98]:
# NumPy array to Tensor

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch reflects numpy's datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
array.dtype

dtype('float64')

In [96]:
tensor.dtype

torch.float64

In [97]:
torch.arange(1.0,8.0).dtype

torch.float32

In [99]:
# change the value of array, what will this do to `tensor`?
# new tensor doesn't changed if we changed array.
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [100]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [101]:
numpy_tensor.dtype

dtype('float32')

In [102]:
# changing tensor , what happens to `numpy_tensor`?
# numpy_tensor doesn't changed.
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducebility ( trying to take random out of random )

In short how a neural network works

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> agian -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does if "flavour" the rendomness.

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [106]:
torch.rand(3,3)

tensor([[0.5807, 0.8714, 0.6495],
        [0.4933, 0.8778, 0.3499],
        [0.3454, 0.9210, 0.5462]])

In [109]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.6438, 0.5983, 0.5925, 0.3511],
        [0.0101, 0.8561, 0.6520, 0.6298],
        [0.6190, 0.0603, 0.7078, 0.8949]])
tensor([[0.2883, 0.6714, 0.5087, 0.1511],
        [0.5524, 0.4878, 0.9314, 0.4880],
        [0.5809, 0.8183, 0.4151, 0.8174]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
# Let's make some random but reproducible tensors

# set the random seed  -> used to initialize a pseudorandom number generator
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rendom_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rendom_tensor_d = torch.rand(3,4)

print(rendom_tensor_c)
print(rendom_tensor_d)
print(rendom_tensor_c == rendom_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects in the GPUs (and making fastr computation)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

In [1]:
!nvidia-smi

Thu Dec  7 08:53:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
#check for GPU access with PyTorch
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.cuda.is_available()


True

For PyTorch since it's capable of running on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## putting tensors (and models) on the GPU



In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU

In [9]:
# If tensor is on GPU, can't tranform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])